# Generated by Django 4.1.2 on 2022-10-14 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=50)),
                (
                    "town",
                    models.CharField(
                        choices=[
                            ("OPUWO", "Opuwo"),
                            ("WINDHOEK", "Windhoek"),
                            ("WARMQUELLE", "Warmquelle"),
                        ],
                        max_length=50,
                        verbose_name="town",
                    ),
                ),
                ("number_of_livestock", models.IntegerField()),
                ("uniqueId", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=500, null=True, unique=True
                    ),
                ),
                (
                    "date_submitted",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "ordering": ["-date_submitted"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "invoice_status",
                    models.CharField(
                        choices=[
                            ("CURRENT", "Current"),
                            ("OVERDUE", "Overdue"),
                            ("PAID", "Paid"),
                        ],
                        default="CURRENT",
                        max_length=50,
                        verbose_name="status",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=100, null=True)),
                ("original_price", models.FloatField()),
                ("discount_price", models.FloatField()),
                ("uniqueId", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=500, null=True, unique=True
                    ),
                ),
                (
                    "date_created",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "date_updated",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        related_query_name="person",
                        to="farmer.client",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
    ]
