# Generated by Django 4.1.2 on 2022-10-14 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="original_price",
            new_name="price_per_livestock",
        ),
    ]
