# Generated by Django 4.1.2 on 2022-10-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0002_rename_original_price_invoice_price_per_livestock"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Invoice",
            new_name="Billing",
        ),
    ]
