# Generated by Django 4.1.2 on 2022-10-14 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0003_rename_invoice_billing"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=500, null=True, unique=True
                    ),
                ),
                (
                    "date_created",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "date_updated",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "billing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="farmer.billing"
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
    ]
