# Generated by Django 4.1.2 on 2022-10-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0004_invoice"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Invoice",
        ),
    ]
