# Generated by Django 4.1.2 on 2022-10-22 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0005_delete_invoice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"ordering": ["-date_join"]},
        ),
        migrations.RenameField(
            model_name="client",
            old_name="date_submitted",
            new_name="date_join",
        ),
    ]
