# Generated by Django 4.1.2 on 2022-10-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0006_alter_client_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billing",
            name="invoice_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("OVERDUE", "Overdue"),
                    ("PAID", "Paid"),
                ],
                default="PENDING",
                max_length=50,
                verbose_name="status",
            ),
        ),
    ]
